# Generated by Django 4.0 on 2022-08-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='automobiili', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=1988),
        ),
    ]
